test: compile() the code.
In some cases, compile() gives us better traceback than exec() alone:

    $ python3.10 -c 'c = open("since-3.11.py").read(); exec(c, {}, {})'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "<string>", line 3
    SyntaxError: asynchronous comprehension outside of an asynchronous function

    $ python3.10 -c 'c = open("since-3.11.py").read(); compile(c, "since-3.11.py", "exec")'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "since-3.11.py", line 3
        async def f(x): [[x async for x in ...] for y in ()]  # Python >= 3.11 is required
                         ^^^^^^^^^^^^^^^^^^^^^^
    SyntaxError: asynchronous comprehension outside of an asynchronous function

The latter is closer to what the user would see:

    $ python3.10 since-3.11.py
      File ".../since-3.11.py", line 3
        async def f(x): [[x async for x in ...] for y in ()]  # Python >= 3.11 is required
                         ^^^^^^^^^^^^^^^^^^^^^^
    SyntaxError: asynchronous comprehension outside of an asynchronous function

With that change, we can stop special-casing Python 3.10.