since-3.7: make version reqmt message show up in traceback.
Fixes missing version requirement message with Python < 3.5 and 3.6.

Before:

    $ python3.4 since-3.7.py
      File "since-3.7.py", line 2
        async def f(x):
                ^
    SyntaxError: invalid syntax

    $ python3.6 since-3.7.py
      File "<fstring>", line 1
        (await x)
               ^
    SyntaxError: invalid syntax

After:

    $ python3.4 since-3.7.py
      File "since-3.7.py", line 2
        async def f(x): f'{await "# Python >= 3.7 is required #"}'
                ^
    SyntaxError: invalid syntax

    $ python3.6 since-3.7.py
      File "<fstring>", line 1
        (await "# Python >= 3.7 is required #")
                                             ^
    SyntaxError: invalid syntax