since-3.7: remove.
Fixes:

    $ python3.8 since-3.7.py
      File "since-3.7.py", line 2
        async for () in 0: ...  # Python >= 3.7 is required
        ^
    SyntaxError: 'async for' outside async function