since-3.11: make version reqmt message show up in traceback.
Fixes missing version requirement message with Python < 3.5, 3.8 and 3.9.

Before:

    $ python3.4 since-3.11.py
      File "since-3.11.py", line 2
        async def f():
                ^
    SyntaxError: invalid syntax

    $ python3.8 since-3.11.py
      File "since-3.11.py", line 0
    SyntaxError: asynchronous comprehension outside of an asynchronous function

    $ python3.9 since-3.11.py
      File ".../since-3.11.py", line 0
    SyntaxError: asynchronous comprehension outside of an asynchronous function

After:

    $ python3.4 since-3.11.py
      File "since-3.11.py", line 1
        match 0:  # Python >= 3.11 is required
              ^
    SyntaxError: invalid syntax

    $ python3.8 since-3.11.py
      File "since-3.11.py", line 1
        match 0:  # Python >= 3.11 is required
              ^
    SyntaxError: invalid syntax

    $ python3.9 since-3.11.py
      File ".../since-3.11.py", line 1
        match 0:  # Python >= 3.11 is required
              ^
    SyntaxError: invalid syntax